name: 'Update data'

on:
  schedule:
    # “Run at minute :05 past hour 0, 4, 8, 12, 16, and 20.”
    - cron: '5 0,4,8,12,16,20 * * *'
  workflow_dispatch:

jobs:
  update-data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'

      - name: Install dependencies
        run: npm install

      - name: Update data
        run: |
          npm run build
          git config user.name 'Tibia highscores bot'
          git config user.email 'highscores@tibiamaps.io'
          git add data
          git commit data -m "Update highscores data" || true
          git push
